### ISSUE TITLE
Best practice and usage of bundles

### ISSUE THREAD

**Issue by giles247** [bernardpeh/songbird#1]
Just started to learn Symfony this week and found your 'book in progress' tonight. As I read the first few chapters I'm left a little uncertain as to the difference between your usage of bundles for each main area of functionality and the symfony website (newish) best practice of using single AppBundle without a namespace. I know everything is technically optional in Symfony, but I just wondered that if your book is aimed a beginners whether it might be less confusing to align it with the best practices? 

That said, I'm also left unsure from Symfony site as to whether this doesn't apply when overriding a vendor bundle e.g. FOSUserBundle i.e. are they saying use single AppBundle most of the time BUT separate out code into separate bundle when overriding a vendor bundle?

**Comment by bernardpeh** [comment]
hi redactuk, this app and book is really work in progress. I didn't expect people to find the site so easily!!

You are right. At the time of writing, I haven't had the chance to implement all the best practices yet. I had to draft out everything and do a first pass of the app and book or else I couldn't start the project at all. I intend to get to the last chapter and do a major restructuring of the code. My greatest fear is that by the time the book/app is finished, things would have changed again and it would be very hard to keep updating. Symfony is great at backwards compatibility but it still sucks to look at the deprecated notices in the debug toolbar. One other consideration I was thinking is to wait for the external libraries (like sonata) to catch up with symfony 3.0. 

You can use single AppBundle most of the time and extend third party bundles within AppBundle. just have to update app/AppKernel.php to init the individual bundle.

**Comment by giles247** [comment]
Thanks for reply. Yes I'm fully aware it's work in progress - just thought feedback might be helpful. I really do like approach you are taking with book i.e. after much research I think full stack + fosuser + sonata admin is base that many people decide to start with. What I will probably do this week is finish reading what you have written so far and trasnpose your bundle suggestions into single one and see how I get on. I'm also more than happy to re-read book again later on and provide any feedback I can - hopefully by then I will have better idea what I'm talking about :)

**Comment by giles247** [comment]
If I spot anything else as I'm working through existing chapters are you ok for me to post as issue or would you prefer me not to?

**Comment by bernardpeh** [comment]
feel free to post but I cant guarantee any fix at this point. cheers
