### ISSUE TITLE
Possible issue in Chapter 7 - Updating Doctrine Fields Automatically

### ISSUE THREAD

**Issue by giles247** [bernardpeh/songbird#2]
Possible issue in Chapter 7 - Updating Doctrine Fields. In suggested code:

```
    public function prePersist()
    {
        // update the modified time
        $this->setModified(new DateTime());

        // for newly created entries
        if ($this->getCreated() == null) {
            $this->setCreated(new DateTime('now'));
        }
        $this->created = new DateTime();
    }
```

The modified date never gets updated. I guessed because there is no function for setModified, but when I created one it still didn't work (probably because I'm not understanding prePersist)

Note: On my setup I also have to add:

```
use \DateTime;
```

at top of code.

**Comment by bernardpeh** [comment]
code has been updated.
